### ISSUE TITLE
Allow to read everything within a folder

### ISSUE THREAD

**Issue by ernestoherrerab** [PaloAltoNetworks/panapi#3]
### Is your feature request related to a problem?

I have tried to retrieve for example all remote networks

I need to enter a specific id or name

### Describe the solution you'd like

I would like to allow the option of not specifying either a name or id so I could retrieve all the data within a folder.

It works now, but being able to retrieve all data at once instead of having to do multiple API calls would be faster.

### Describe alternatives you've considered

    def read(self, session):
        if session.is_expired:
            session.reauthenticate()
        url = self._base_url + self._endpoint
        if hasattr(self, 'folder'):
            params = {'folder': self.folder}
        else:
            params = {}
        has_id = hasattr(self, 'id')
        has_name = hasattr(self, 'name')
        if has_id:
            url = self._base_url + self._endpoint + '/{}'.format(self.id)
        elif has_name:
            params.update({'name': self.name})
        else:
            raise ValueError('name or id value is required'

send the API cal with only the "folder" value, and add error handling depending on the response.

### Additional context

If I want to test if a list of remote networks already exists I would need to make pultiple API calls instead of doing one API call and then handle the data in python.

**Comment by stealthllama** [comment]
This should already be provided by the list method.  You can create an object with just the folder parameter and then perform a list to retrieve the entire collection of resources for that object type.
