### ISSUE TITLE
Location() class when applied with "read()"  error

### ISSUE THREAD

**Issue by ernestoherrerab** [PaloAltoNetworks/panapi#4]
## Describe the bug

The Location() class when applied with "read()" throws an error due to the following:
config = result['data'][0]
TypeError: list indices must be integers or slices, not str

## Expected behavior

We should get the output of the API call for the Location class.

## Current behavior
Error is thrown due to Location() being forced to have a "name" attribute which does not exist in the API call and the conditional loop on line 71 of the __init__.py catches this and applies the following:
config = result['data'][0]

however the result is a list of dictionaries, hence there is no key called "data" in the result causing the error.

TypeError: list indices must be integers or slices, not str

## Possible solution
I added the following temporary fix for my specific use case, however I am not sure if this will affect other functionality.

                elif has_name:
                    if "data" in result:
                        config = result["data"][0]
                        return type(self)(**config)
                    else:
                        return type(self)(**result)

## Steps to reproduce

def get_region(session):
    """ Get Region Name based on Location """

    region_id = Location()
    response = region_id.read(session)
    return response 

1.
2.
3.
4.

## Context

Trying to provision remote networks, but need the region id captured from somewhere mapped to the region name available in palo alto documentation

## Your Environment

- Version used: 
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Python 3.9.5
- Operating System and version (desktop or mobile): Ubuntu WSL 
- Link to your project: Not published yet.

**Comment by stealthllama** [comment]
The read method is used in conjunction with a specific id reference.  To retrieve all locations you'll need to use the list method.
